env:
  node: true
  mocha: true
  es6: true 
extends: 'eslint:recommended'
plugins:
    - json
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - always
parserOptions:
  sourceType: module
